//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistik_Permit
{
    using System;
    using System.Collections.Generic;
    
    public partial class form_pinjam
    {
        public string id_form { get; set; }
        public string date { get; set; }
        public string id_borrower { get; set; }
        public string name { get; set; }
        public string list { get; set; }
    
        public virtual peminjam peminjam { get; set; }
    }
}
