//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistik_Permit
{
    using System;
    using System.Collections.Generic;
    
    public partial class logistik
    {
        public string Id_logistik { get; set; }
        public string nama { get; set; }
        public string jenis_barang { get; set; }
        public int jumlah { get; set; }
        public string kepemilikan { get; set; }
        public string keterangan { get; set; }
        public string update_by { get; set; }
    }
}
